name: webdav

services:
  webdav:
    image: ghcr.io/hacdias/webdav:v5.10
    restart: unless-stopped
    container_name: webdav
    ports:
      - 6065:6065
    environment:
      WEBDAV_USERNAME: "${WEBDAV_USERNAME}"
      WEBDAV_PASSWORD: "${WEBDAV_PASSWORD}"
    volumes:
      - /home/milan/data/webdav:/data
      - ./config.yml:/config.yml:ro
    command: ["--config", "/config.yml"]
