http:
  routers:
    vogon-backend:
      rule: Host(`api.vogon.marcinco.xyz`)
      entryPoints:
        - http
      service: vogon-backend

    vogon-emqx-dashboadr:
      rule: Host(`emqx.vogon.marcinco.xyz`)
      entryPoints:
        - http
      service: vogon-emqx-dashboard

  services:
    vogon-backend:
      loadBalancer:
        servers:
          - url: http://localhost:8000

    vogon-emqx-dashboard:
      loadBalancer:
        servers:
          - url: http://localhost:8003

tcp:
  routers:
    vogon-emqx:
      rule: HostSNI(`mqtt.vogon.marcinco.xyz`)
      entryPoints:
        - mqtts
      service: vogon-emqx
      tls:
        passthrough: true

  services:
    vogon-emqx:
      loadBalancer:
        servers:
          - address: localhost:8002
